### PR TITLE
Feature/implement commands from readme: Add `ccm-yaml` command

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #1

### CODE REVIEW

**Comment by CAMOBAP** [comment]
Not ready for review still in progress

**Comment by ronaldtse** [comment]
@CAMOBAP795 any updates? Thanks!

**Comment by ronaldtse** [comment]
I restructured the gem and it is much cleaner now for implementing additional commands. Going to merge this first.

**Comment by CAMOBAP** [comment]
@ronaldtse can I continue with other commands?

**Comment by ronaldtse** [comment]
Yes, please do!

**Pull request merged**
